### ISSUE TITLE
Python library deletions 

### ISSUE THREAD

**Issue by jainavana** [k2-fsa/sherpa-onnx#1233]
Hello, 

We have been using the sherpa-onnx python library for the past few months. Thank you for all your hard work! 

Over the last few weeks, we have noticed that minor versions of the library seem to be deleted at times when attempting to pull them. For instance, 1.10.16 has disappeared from this [list](https://pypi.org/project/sherpa-onnx/#history) while it was available approximately 2 weeks ago. Is there a strategy by which we can reliably choose versions that wont be delisted? Any help here would be appreciated.

**Comment by csukuangfj** [comment]
Sorry for the inconvenience.

We.MUST.delete previous releases to free spaces since pypi.org only provides 10GB space for open source projects.
If the space is full, it refuses us to release new versions.

As an alternative, all previous releases (since 1.10.16) can be found at
https://k2-fsa.github.io/sherpa/onnx/cpu.html

To use it, you can replace `pip install sherpa-onnx==1.10.16` with the following command
```
pip install sherpa-onnx==1.10.16 -f https://k2-fsa.github.io/sherpa/onnx/cpu.html
```
<img width="1011" alt="Screenshot 2024-08-08 at 08 34 41" src="https://github.com/user-attachments/assets/da1b914f-29ae-4ac9-aa19-709a0a3d9135">


---

Alternatively, if you are using `requirements.txt`, then you can add the following two lines to `requirements.txt`:
```
-f https://k2-fsa.github.io/sherpa/onnx/cpu.html
sherpa-onnx==1.10.16
```

and then use `pip install -r requirements.txt`.

<img width="1007" alt="Screenshot 2024-08-08 at 08 37 29" src="https://github.com/user-attachments/assets/0f324ddb-0404-442b-bc34-02be34faf6c5">

---

Another method is to use
```
pip install https://huggingface.co/csukuangfj/sherpa-onnx-wheels/resolve/main/cpu/1.10.16/sherpa_onnx-1.10.16-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```
<img width="999" alt="Screenshot 2024-08-08 at 08 38 54" src="https://github.com/user-attachments/assets/d4c3e7f6-bf63-465d-993b-0744eb2e6b6f">

---

To give you one more method:
```
wget https://huggingface.co/csukuangfj/sherpa-onnx-wheels/resolve/main/cpu/1.10.16/sherpa_onnx-1.10.16-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

pip install ./sherpa_onnx-1.10.16-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```

<img width="1008" alt="Screenshot 2024-08-08 at 08 41 27" src="https://github.com/user-attachments/assets/d83e953b-39df-4bcf-ae58-d2311f0281b4">


---

You can choose any one of the methods as you wish.

**Comment by csukuangfj** [comment]
By the way, we have described it in the documentation. Please see
https://k2-fsa.github.io/sherpa/onnx/python/install.html#method-1-from-pre-compiled-wheels-cpu-only

![Screenshot 2024-08-08 at 08 43 55](https://github.com/user-attachments/assets/a211f39c-56e6-468c-9fbc-ccd10f8e7182)

**Comment by jainavana** [comment]
Thank you! @csukuangfj. That solves my issue.
