### ISSUE TITLE
[Help wanted] Support the latest zipformer (streaming + non-streaming) from icefall

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/sherpa-onnx#174]
https://github.com/k2-fsa/icefall/pull/1108 adds support to export the latest zipformer to ONNX (both streaming and non-streaming are supported).

We need to support the exported models in sherpa-onnx.

@kakashidan 

---

We also need to update the doc:
- https://k2-fsa.github.io/sherpa/onnx/pretrained_models/online-transducer/zipformer-transducer-models.html
- https://k2-fsa.github.io/sherpa/onnx/pretrained_models/offline-transducer/zipformer-transducer-models.html

**Comment by kafan1986** [comment]
@csukuangfj I have tested latest Zipformer with Sherpa ONNX and it works. But the streaming ASR is not working with Sherpa and gives error.

**Comment by csukuangfj** [comment]
Could you post your error log?

**Comment by kafan1986** [comment]
> Could you post your error log?

./sherpa-onnx/sherpa-onnx/csrc/online-transducer-model.cc:GetModelType:69 Unsupported model_type: zipformer2
./sherpa-onnx/sherpa-onnx/csrc/online-transducer-model.cc:Create:92 Unknown model type in online transducer!
Segmentation fault

**Comment by csukuangfj** [comment]
> > Could you post your error log?
> 
> 
> 
> ./sherpa-onnx/sherpa-onnx/csrc/online-transducer-model.cc:GetModelType:69 Unsupported model_type: zipformer2
> 
> ./sherpa-onnx/sherpa-onnx/csrc/online-transducer-model.cc:Create:92 Unknown model type in online transducer!
> 
> Segmentation fault

I see. That is exactly what this issue is targeting at.

Please wait for a moment before this issue is resolved.

**Comment by kafan1986** [comment]
@csukuangfj Any update on this issue? Thanks for looking into this.

**Comment by csukuangfj** [comment]
> @csukuangfj Any update on this issue? Thanks for looking into this.

A community contributor is working on it.  It may take a week.

**Comment by kafan1986** [comment]
> 

Hello. @csukuangfj @kakashidan  Any update on this request? Thanks once again.

**Comment by kakashidan** [comment]
> > 
> 
> Hello. @csukuangfj @kakashidan Any update on this request? Thanks once again.

#185 I finished a draft version which could run normally. But the code is not clean enough and I will refactor it later

**Comment by bhaswa** [comment]
I tested the latest streaming Zipformer with Sherpa ONNX C++. Now it works with normal onnx verion but it gives error with int8 quantization onnx models. It gives the below error

 what():  Failed to load model with error: /onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:46 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 19 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain com.ms.internal.nhwc is till opset 18.

**Comment by csukuangfj** [comment]
> I tested the latest streaming Zipformer with Sherpa ONNX C++. Now it works with normal onnx verion but it gives error with int8 quantization onnx models. It gives the below error
> 
> what(): Failed to load model with error: /onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:46 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::basic_string, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only _guarantees_ support for models stamped with official released onnx opset versions. Opset 19 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain com.ms.internal.nhwc is till opset 18.

Have you made any changes to sherpa-onnx? It works fine on my side.

**Comment by bhaswa** [comment]
No, there are no changes to sherpa-onnx. After pulling latest changes onnx model without int8 quantization works. But models with int8 quantization is giving error.

**Comment by csukuangfj** [comment]
Have you made any changes to icefall?

I have made a streaming int8 zipformer model available at
https://huggingface.co/csukuangfj/sherpa-onnx-streaming-zipformer-en-2023-06-26

Could you try it?

**Comment by csukuangfj** [comment]
> No, there are no changes to sherpa-onnx. After pulling latest changes onnx model without int8 quantization works. But models with int8 quantization is giving error.

@bhaswa 

I think I know the reason. 

Your local Python package `onnxruntime` must be newer than 1.14.0

`sherpa-onnx` is using onnxruntime v1.14.0, so please use
```
pip install "onnxruntime<=1.14.0"
```
before you export the model in icefall.

Otherwise, you need to upgrade `onnxruntime` in
https://github.com/k2-fsa/sherpa-onnx/blob/master/cmake/onnxruntime.cmake


---

By the way, I am using `onnxruntime==1.13.0` in my Python environment and that is why I have not encountered the same issue like you.

**Comment by bhaswa** [comment]
Thanks @csukuangfj The reason was indeed the onnxruntime version. My local onnxruntime version was 1.15.0. After changing the version to 1.14.0, now it is working.

**Comment by yangy1992** [comment]
the sherpa-onnx is tested ok when giving the single wav, bus it fails when testing two or three wavs. The log is below 
--------------------------------------------------------------------------------------------
[yangyan@cortana build]$ ./bin/sherpa-onnx --tokens=models/data/lang_bpe_500/tokens.txt  --encoder=models/exp/encoder-epoch-30-avg-1-chunk-16-left-128.onnx  --decoder=models/exp/decoder-epoch-30-avg-1-chunk-16-left-128.onnx  --joiner=models/exp/joiner-epoch-30-avg-1-chunk-16-left-128.onnx  --provider=cpu --num-threads=1 models/test_wavs/1089-134686-0001.wav models/test_wavs/1089-134686-0001.wav
/home/yangyan/code/sherpa-onnx/sherpa-onnx/csrc/parse-options.cc:Read:361 ./bin/sherpa-onnx --tokens=models/data/lang_bpe_500/tokens.txt --encoder=models/exp/encoder-epoch-30-avg-1-chunk-16-left-128.onnx --decoder=models/exp/decoder-epoch-30-avg-1-chunk-16-left-128.onnx --joiner=models/exp/joiner-epoch-30-avg-1-chunk-16-left-128.onnx --provider=cpu --num-threads=1 models/test_wavs/1089-134686-0001.wav models/test_wavs/1089-134686-0001.wav 

OnlineRecognizerConfig(feat_config=FeatureExtractorConfig(sampling_rate=16000, feature_dim=80), model_config=OnlineTransducerModelConfig(encoder_filename="models/exp/encoder-epoch-30-avg-1-chunk-16-left-128.onnx", decoder_filename="models/exp/decoder-epoch-30-avg-1-chunk-16-left-128.onnx", joiner_filename="models/exp/joiner-epoch-30-avg-1-chunk-16-left-128.onnx", tokens="models/data/lang_bpe_500/tokens.txt", num_threads=1, provider="cpu", debug=False), lm_config=OnlineLMConfig(model="", scale=0.5), endpoint_config=EndpointConfig(rule1=EndpointRule(must_contain_nonsilence=False, min_trailing_silence=2.4, min_utterance_length=0), rule2=EndpointRule(must_contain_nonsilence=True, min_trailing_silence=1.2, min_utterance_length=0), rule3=EndpointRule(must_contain_nonsilence=False, min_trailing_silence=0, min_utterance_length=20)), enable_endpoint=True, max_active_paths=4, decoding_method="greedy_search")
2023-06-27 11:20:04.795647548 [E:onnxruntime:, sequential_executor.cc:494 ExecuteKernel] Non-zero status code returned while running Concat node. Name:'Concat_131' Status Message: concat.cc:154 PrepareForCompute Non concat axis dimensions must match: Axis 0 has mismatched dimensions of 1 and 2
Aborted
--------------------------------------------------------------------------
the model i used is https://huggingface.co/Zengwei/icefall-asr-librispeech-streaming-zipformer-2023-05-17.

i think the reason is that the batchsize is above 1 when testing more wavs, so it crashed.

**Comment by csukuangfj** [comment]
> ## the sherpa-onnx is tested ok when giving the single wav, bus it fails when testing two or three wavs. The log is below
> [yangyan@cortana build]$ ./bin/sherpa-onnx --tokens=models/data/lang_bpe_500/tokens.txt --encoder=models/exp/encoder-epoch-30-avg-1-chunk-16-left-128.onnx --decoder=models/exp/decoder-epoch-30-avg-1-chunk-16-left-128.onnx --joiner=models/exp/joiner-epoch-30-avg-1-chunk-16-left-128.onnx --provider=cpu --num-threads=1 models/test_wavs/1089-134686-0001.wav models/test_wavs/1089-134686-0001.wav /home/yangyan/code/sherpa-onnx/sherpa-onnx/csrc/parse-options.cc:Read:361 ./bin/sherpa-onnx --tokens=models/data/lang_bpe_500/tokens.txt --encoder=models/exp/encoder-epoch-30-avg-1-chunk-16-left-128.onnx --decoder=models/exp/decoder-epoch-30-avg-1-chunk-16-left-128.onnx --joiner=models/exp/joiner-epoch-30-avg-1-chunk-16-left-128.onnx --provider=cpu --num-threads=1 models/test_wavs/1089-134686-0001.wav models/test_wavs/1089-134686-0001.wav
> 
> ## OnlineRecognizerConfig(feat_config=FeatureExtractorConfig(sampling_rate=16000, feature_dim=80), model_config=OnlineTransducerModelConfig(encoder_filename="models/exp/encoder-epoch-30-avg-1-chunk-16-left-128.onnx", decoder_filename="models/exp/decoder-epoch-30-avg-1-chunk-16-left-128.onnx", joiner_filename="models/exp/joiner-epoch-30-avg-1-chunk-16-left-128.onnx", tokens="models/data/lang_bpe_500/tokens.txt", num_threads=1, provider="cpu", debug=False), lm_config=OnlineLMConfig(model="", scale=0.5), endpoint_config=EndpointConfig(rule1=EndpointRule(must_contain_nonsilence=False, min_trailing_silence=2.4, min_utterance_length=0), rule2=EndpointRule(must_contain_nonsilence=True, min_trailing_silence=1.2, min_utterance_length=0), rule3=EndpointRule(must_contain_nonsilence=False, min_trailing_silence=0, min_utterance_length=20)), enable_endpoint=True, max_active_paths=4, decoding_method="greedy_search")
> 2023-06-27 11:20:04.795647548 [E:onnxruntime:, sequential_executor.cc:494 ExecuteKernel] Non-zero status code returned while running Concat node. Name:'Concat_131' Status Message: concat.cc:154 PrepareForCompute Non concat axis dimensions must match: Axis 0 has mismatched dimensions of 1 and 2
> Aborted
> the model i used is https://huggingface.co/Zengwei/icefall-asr-librispeech-streaming-zipformer-2023-05-17.
> 
> i think the reason is that the batchsize is above 1 when testing more wavs, so it crashed.

Fixed by https://github.com/k2-fsa/icefall/pull/1148

**Comment by csukuangfj** [comment]
Closing as it has been fixed.
