### ISSUE TITLE
offline zipformer2 int8 issue

### ISSUE THREAD

**Issue by joazoa** [k2-fsa/sherpa-onnx#188]
When i try the int8 version of the offline onnx zipformer2, get this error:
  what():  Failed to load model with error: /onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:46 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 19 is under development and suppor
t for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain com.ms.internal.nhwc is till opset 18.

the plain onnx version works fine.

Both the export and the attempted inference is done on the same installation.

**Comment by csukuangfj** [comment]
Have you fixed it?

If not, please downgrade your onnxruntime python package from 1.15.0 to 1.14.0 or below and re-export your model.

Even though you didn't mention the version of your onnxruntime python package, it must be 1.15.0 or above, otherwise you wouldn't get such an error.

Another fix is to upgrade the onnxruntime from 1.14.0 to 1.15.0 or above in sherpa-onnx.

**Comment by joazoa** [comment]
Thank you!

I confirm that pip3 install onnxruntime==1.14.0 before export resolves the issue.

**Comment by csukuangfj** [comment]
Closing as it has been fixed.
