### ISSUE TITLE
Add punctuation to the output of speech-to-text

### ISSUE THREAD

**Issue by lightfate** [k2-fsa/sherpa-onnx#236]
Hello,

I'm currently using sherpa-onnx to transcribe audio files. It works well in terms of transcribing the spoken words into text, but I noticed that the output text does not contain any punctuation. This makes it a bit hard to read and understand the transcribed text, especially when it's a long paragraph.

I'm writing to kindly ask if you could provide some insights or methods for adding punctuation to the transcribed text. Any guidance on how this could be achieved would be greatly appreciated.

Thank you for your time and assistance.

**Comment by csukuangfj** [comment]
@lightfate 

If you are using a non-streaming model, then you can use our newly added whisper model, which outputs punctuation marks along with the recognition result.  You can find the doc at 
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/whisper/index.html


If you want to use your own model or to use a streaming ASR model, you need to use an external punctuation model to process your recognition result so that it contains punctuation marks.  

You can find such a model by searching GitHub, e.g.,

https://github.com/topics/punctuation-restoration

**Comment by csukuangfj** [comment]
@lightfate 

Please see
https://k2-fsa.github.io/sherpa/onnx/punctuation/index.html

We just added punctuation support. The model in the above URL supports both Chinese and English.
