### ISSUE TITLE
TTS engine crashes android settings

### ISSUE THREAD

**Issue by nanaghartey** [k2-fsa/sherpa-onnx#670]
On android when you change preferred TTS engine to use SherpaOnnxTTS engine, synthesis fails even if app is kept in background. Synthesis only works in the app itself when you input something and tap "test". 

Another issue is, when you go back to android settings to change preferred TTS engine, the settings screen crashes. 

You have to uninstall SherpaTTS engine before you can revert to Google tts engine. 

My device is pixel4XL

**Comment by csukuangfj** [comment]
Which version of sherpa-onnx are you using?

**Comment by nanaghartey** [comment]
Looks like a version mismatch issue. I've solved it and i'm closing the issue now. Thanks

**Comment by klasrocket** [comment]
I got similar problems, using version 1.9.17 on android 13 (lineageOS without GSF and microG) , the settings page for Text-to-speech in android system settings crashes. 
@nanaghartey what versions did you use, and what versions did you get working?

**Comment by csukuangfj** [comment]
> I got similar problems, using version 1.9.17 on android 13 (lineageOS without GSF and microG, on a samsung s10e Enoxys) , the settings page for Text-to-speech in android system settings crashes. 
> @nanaghartey what versions did you use, and what versions did you get working?

could you post logcat output?

**Comment by klasrocket** [comment]
Below is output from `adb logcat | grep settings`
Not sure if there might be more interesting stuff that got filtered out by command above.

```
04-11 17:20:52.812  6334  6406 I ActivityTaskManager: Displayed com.android.settings/.SubSettings: +150ms
04-11 17:20:52.812  6334  6406 I ActivityTaskManager: Fully drawn com.android.settings/.SubSettings: +150ms
04-11 17:21:37.525  6334 13313 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from uid 1000
04-11 17:21:37.565 25736 25736 D SettingsActivity: Switching to fragment com.android.settings.language.LanguageAndInputSettings
04-11 17:21:37.565 25736 25736 D SubSettings: Launching fragment com.android.settings.language.LanguageAndInputSettings
04-11 17:21:37.573 25736 25736 D PrefCtrlListHelper: Could not find Context-only controller for pref: com.android.settings.applications.appinfo.ManageAppLocalePreferenceController
04-11 17:21:37.573 25736 25736 W PrefCtrlListHelper: Cannot instantiate controller from reflection: com.android.settings.applications.appinfo.ManageAppLocalePreferenceController
04-11 17:21:37.573 25736 25736 D PrefCtrlListHelper: Could not find Context-only controller for pref: com.android.settings.language.OnDeviceRecognitionPreferenceController
04-11 17:21:37.573 25736 25736 D PrefCtrlListHelper: Could not find Context-only controller for pref: com.android.settings.language.UserDictionaryPreferenceController
04-11 17:21:37.573 25736 25736 D PrefCtrlListHelper: Could not find Context-only controller for pref: com.android.settings.inputmethod.GameControllerPreferenceController
04-11 17:21:37.573 25736 25736 D PrefCtrlListHelper: Could not find Context-only controller for pref: com.android.settings.core.WorkPreferenceController
04-11 17:21:37.574 25736 25736 D PrefCtrlListHelper: Could not find Context-only controller for pref: com.android.settings.inputmethod.SpellCheckerForWorkPreferenceController
04-11 17:21:37.650  6334 13313 D CoreBackPreview: Window{b476f16 u0 com.android.settings/com.android.settings.SubSettings}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@4e7e284, mPriority=-1}
04-11 17:21:37.701  6334  6406 I ActivityTaskManager: Displayed com.android.settings/.SubSettings: +175ms
04-11 17:21:37.701  6334  6406 I ActivityTaskManager: Fully drawn com.android.settings/.SubSettings: +175ms
04-11 17:21:38.189 25736 25736 D DashboardFragment: unregister observer: @da41c89, uri: content://com.android.settings.dashboard.SummaryProvider/user
04-11 17:21:42.040  6334 13160 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from uid 1000
04-11 17:21:42.083 25736 25736 D SettingsActivity: Switching to fragment com.android.settings.tts.TextToSpeechSettings
04-11 17:21:42.083 25736 25736 D SubSettings: Launching fragment com.android.settings.tts.TextToSpeechSettings
04-11 17:21:42.125  6334 17450 D CoreBackPreview: Window{136118b u0 com.android.settings/com.android.settings.SubSettings}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@7ffa326, mPriority=-1}
04-11 17:21:42.233 25736 25736 E AndroidRuntime: Process: com.android.settings, PID: 25736
04-11 17:21:42.233 25736 25736 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=147640776, result=1, data=Intent { (has extras) }} to activity {com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
04-11 17:21:42.233 25736 25736 E AndroidRuntime: 	at com.android.settings.tts.TextToSpeechSettings.updateDefaultLocalePref(TextToSpeechSettings.java:526)
04-11 17:21:42.233 25736 25736 E AndroidRuntime: 	at com.android.settings.tts.TextToSpeechSettings.onActivityResult(TextToSpeechSettings.java:509)
04-11 17:21:42.233 25736 25736 E AndroidRuntime: 	at com.android.settings.SettingsActivity.onActivityResult(SettingsActivity.java:541)
04-11 17:21:42.239  6334  6848 W ActivityTaskManager:   Force finishing activity com.android.settings/.SubSettings
04-11 17:21:42.241  6334  6848 W ActivityTaskManager:   Force finishing activity com.android.settings/.SubSettings
04-11 17:21:42.336  6334  7073 I ActivityManager: Process com.android.settings (pid 25736) has died: fg  TOP 
04-11 17:21:42.336  6334  6848 I WindowManager: WIN DEATH: Window{9774d40 u0 com.android.settings/com.android.settings.homepage.SettingsHomepageActivity}
04-11 17:21:42.337  6334  6848 W InputManager-JNI: Input channel object '9774d40 com.android.settings/com.android.settings.homepage.SettingsHomepageActivity (client)' was disposed without first being removed with the input manager!
04-11 17:21:42.338  6334 19413 I WindowManager: WIN DEATH: Window{b476f16 u0 com.android.settings/com.android.settings.SubSettings}
04-11 17:21:42.338  6334 19413 W InputManager-JNI: Input channel object 'b476f16 com.android.settings/com.android.settings.SubSettings (client)' was disposed without first being removed with the input manager!
04-11 17:21:42.339  6334  6461 I WindowManager: WIN DEATH: Window{136118b u0 com.android.settings/com.android.settings.SubSettings}
04-11 17:21:42.339  6334  6461 W InputManager-JNI: Input channel object '136118b com.android.settings/com.android.settings.SubSettings (client)' was disposed without first being removed with the input manager!
04-11 17:21:42.341  6334  8455 I WindowManager: WIN DEATH: Window{b70d28b u0 com.android.settings/com.android.settings.SubSettings}
04-11 17:21:42.341  6334  8455 W InputManager-JNI: Input channel object 'b70d28b com.android.settings/com.android.settings.SubSettings (client)' was disposed without first being removed with the input manager!
04-11 17:21:42.349  6334  6415 W UsageStatsService: Unexpected activity event reported! (com.android.settings/com.android.settings.SubSettings event : 23 instanceId : 233832465)
04-11 17:21:42.349  6334  6415 W UsageStatsService: Unexpected activity event reported! (com.android.settings/com.android.settings.homepage.SettingsHomepageActivity event : 23 instanceId : 262002726)
04-11 17:21:42.371  6334  6417 I ActivityManager: Start proc 30599:com.android.settings/1000 for top-activity {com.android.settings/com.android.settings.SubSettings}
04-11 17:21:42.410 30599 30599 W ndroid.settings: ClassLoaderContext shared library size mismatch. Expected=3, found=1 (PCL[]{PCL[/system/framework/org.apache.http.legacy.jar*3751013904]#PCL[/system/system_ext/framework/androidx.window.extensions.jar*2492971845]#PCL[/system/system_ext/framework/androidx.window.sidecar.jar*1246234447]} | PCL[]{PCL[/system/framework/org.apache.http.legacy.jar*3751013904]})
04-11 17:21:42.412 30599 30599 E ndroid.settings: Dex checksum does not match for dex: /system/system_ext/priv-app/Settings/Settings.apk.Expected: 1558488465, actual: 2589242961
04-11 17:21:42.422 30599 30599 V GraphicsEnvironment: ANGLE Developer option for 'com.android.settings' set to: 'default'
04-11 17:21:42.423 30599 30599 V GraphicsEnvironment: ANGLE GameManagerService for com.android.settings: false
04-11 17:21:42.489 30599 30599 D PrefCtrlListHelper: Could not find Context-only controller for pref: com.android.settings.datetime.DateTimePreferenceController
04-11 17:21:42.490 30599 30599 D PrefCtrlListHelper: Could not find Context-only controller for pref: com.android.settings.system.ResetPreferenceController
04-11 17:21:42.529 30599 30599 D DashboardFragment: register observer: @92c655b, uri: content://com.android.settings.dashboard.SummaryProvider/user
04-11 17:21:42.637  6334  6410 W WindowManager: Exception thrown during dispatchAppVisibility Window{b476f16 u0 com.android.settings/com.android.settings.SubSettings EXITING}
04-11 17:21:42.642  6334  7073 D CoreBackPreview: Window{f0dd41f u0 com.android.settings/com.android.settings.SubSettings}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@9c24404, mPriority=-1}
04-11 17:21:42.740  6334  6409 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{5c7a695 u0 com.android.settings/.SubSettings} t-1 f}}
```

**Comment by woheller69** [comment]
Somehow I killed all TTS options for my device. Settings will crash. And even if I uninstall all TTS apps including Google TTS it does not work after reinstall of Google TTS 

Process: com.android.settings, PID: 15334
 java.lang.RuntimeException: Failure delivering result ResultInfo{w
 	at android.app.ActivityThread.deliverResults(ActivityThread.jav
 	at android.app.ActivityThread.handleSendResult(ActivityThread.j
 	at android.app.servertransaction.ActivityResultItem.execute(Act
 	at android.app.servertransaction.ActivityTransactionItem.execut
 	at android.app.servertransaction.TransactionExecutor.executeCal
 	at android.app.servertransaction.TransactionExecutor.execute(Tr
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.ja
 	at android.os.Handler.dispatchMessage(Handler.java:106)
 	at android.os.Looper.loopOnce(Looper.java:201)
 	at android.os.Looper.loop(Looper.java:288)
 	at android.app.ActivityThread.main(ActivityThread.java:7918)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtu
 	at android.speech.tts.TtsEngines.parseEnginePrefFromList(TtsEng
 	at android.speech.tts.TtsEngines.isLocaleSetToDefaultForEngine(
 	at com.android.settings.tts.TextToSpeechSettings.updateDefaultL
 	at com.android.settings.tts.TextToSpeechSettings.onActivityResu
 	at androidx.fragment.app.FragmentManager$7.onActivityResult(Fra
 	at androidx.fragment.app.FragmentManager$7.onActivityResult(Fra
 	at androidx.activity.result.ActivityResultRegistry.doDispatch(A
 	at androidx.activity.result.ActivityResultRegistry.dispatchResu
 	at androidx.activity.ComponentActivity.onActivityResult(Compone
 	at androidx.fragment.app.FragmentActivity.onActivityResult(Frag
 	at com.android.settings.SettingsActivity.onActivityResult(Setti
 	at android.app.Activity.dispatchActivityResult(Activity.java:86
 	at android.app.ActivityThread.deliverResults(ActivityThread.jav
 	at android.app.ActivityThread.handleSendResult(ActivityThread.j
 	at android.app.servertransaction.ActivityResultItem.execute(Act
 	at android.app.servertransaction.ActivityTransactionItem.execut
 	at android.app.servertransaction.TransactionExecutor.executeCal
 	at android.app.servertransaction.TransactionExecutor.execute(Tr
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.ja
 	at android.os.Handler.dispatchMessage(Handler.java:106) 
 	at android.os.Looper.loopOnce(Looper.java:201) 
 	at android.os.Looper.loop(Looper.java:288) 
 	at android.app.ActivityThread.main(ActivityThread.java:7918) 
 	at java.lang.reflect.Method.invoke(Native Method) 
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by woheller69** [comment]
I crashed the settings for TTS engine completely. It does not work even if I uninstall all TTS engines including Google TTS and then reinstall just Google TTS:  

"Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference"


FATAL EXCEPTION: main
Process: com.android.settings, PID: 16208
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1987472593, result=1, data=Intent { (has extras) }} to activity {com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5338)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5377)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at android.speech.tts.TtsEngines.parseEnginePrefFromList(TtsEngines.java:510)
	at android.speech.tts.TtsEngines.isLocaleSetToDefaultForEngine(TtsEngines.java:372)
	at com.android.settings.tts.TextToSpeechSettings.updateDefaultLocalePref(TextToSpeechSettings.java:526)
	at com.android.settings.tts.TextToSpeechSettings.onActivityResult(TextToSpeechSettings.java:509)

**Comment by woheller69** [comment]
Fixed with

    adb shell settings put secure "tts_default_synth" com.google.android.tts

Before that:
    adb shell settings get secure tts_default_synth
    -> null

Even complete reinstallation of LineageOS did not fix it. But the adb command solved it :-)

**Comment by StyXman** [comment]
I did a similar one to make SherpaTTS work:

```
$ sudo adb shell settings put secure "tts_default_synth" org.woheller69.ttsengine
$ sudo adb shell settings get secure tts_default_synth
org.woheller69.ttsengine
```
